import type { TvShow } from "../types/TvShow";

export const mockTvShows: TvShow[] = [
  {
    id: 1,
    url: "url1",
    name: "Breaking Bad",
    type: "Scripted",
    language: "English",
    genres: ["Drama", "Crime"],
    status: "Ended",
    runtime: 60,
    averageRuntime: 60,
    premiered: "2008-01-20",
    ended: "2013-09-29",
    officialSite: "https://www.amc.com/shows/breaking-bad",
    schedule: { time: "21:00", days: ["Sunday"] },
    rating: { average: 9.5 },
    weight: 100,
    network: {
      id: 1,
      name: "AMC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.amc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: null, thetvdb: 81189, imdb: "tt0903747" },
    image: { medium: "", original: "" },
    summary: "A high school chemistry teacher turned methamphetamine producer.",
    updated: 0,
    _links: { self: { href: "" } },
  },
  {
    id: 2,
    url: "url2",
    name: "Friends",
    type: "Scripted",
    language: "English",
    genres: ["Comedy", "Romance"],
    status: "Ended",
    runtime: 30,
    averageRuntime: 30,
    premiered: "1994-09-22",
    ended: "2004-05-06",
    officialSite: "https://www.nbc.com/friends",
    schedule: { time: "20:00", days: ["Thursday"] },
    rating: { average: 8.9 },
    weight: 90,
    network: {
      id: 2,
      name: "NBC",
      country: {
        name: "United States",
        code: "US",
        timezone: "America/New_York",
      },
      officialSite: "https://www.nbc.com/",
    },
    webChannel: null,
    dvdCountry: null,
    externals: { tvrage: null, thetvdb: 79168, imdb: "tt0108778" },
    image: { medium: "", original: "" },
    summary: "Follows the personal and professional lives of six friends.",
    updated: 0,
    _links: { self: { href: "" } },
  },
];
