import type { TvShow } from "../types/TvShow";

export const mockTvShows: TvShow[] = [
  {
    id: 1,
    name: "Breaking Bad",
    language: "English",
    genres: ["Drama", "Crime"],
    rating: { average: 9.5 },
    premiered: "2008-01-20",
    officialSite: "https://www.amc.com/shows/breaking-bad",
    image: { medium: "", original: "" },
    summary: "A high school chemistry teacher turned methamphetamine producer.",
  },
  {
    id: 2,
    name: "Friends",
    language: "English",
    genres: ["Comedy", "Romance"],
    rating: { average: 8.9 },
    premiered: "1994-09-22",
    officialSite: "https://www.nbc.com/friends",
    image: { medium: "", original: "" },
    summary: "Follows the personal and professional lives of six friends.",
  },
  {
    id: 3,
    name: "The Sopranos",
    language: "English",
    genres: ["Drama", "Crime"],
    rating: { average: 9.2 },
    premiered: "1999-01-10",
    officialSite: "https://www.hbo.com/the-sopranos",
    image: { medium: "", original: "" },
    summary: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life.",
  },
  {
    id: 4,
    name: "Brooklyn Nine-Nine",
    language: "English",
    genres: ["Comedy", "Crime"],
    rating: { average: 8.4 },
    premiered: "2013-09-17",
    officialSite: "https://www.nbc.com/brooklyn-nine-nine",
    image: { medium: "", original: "" },
    summary: "A group of detectives in a Brooklyn precinct solve crimes while keeping things light and funny.",
  },
  {
    id: 5,
    name: "How I Met Your Mother",
    language: "English",
    genres: ["Comedy", "Romance"],
    rating: { average: 8.3 },
    premiered: "2005-09-19",
    officialSite: "https://www.cbs.com/shows/how-i-met-your-mother/",
    image: { medium: "", original: "" },
    summary: "A father recounts to his children the events that led him to meet their mother, through comedic and romantic adventures.",
  },
];
